### ISSUE TITLE
Looking for a workaround for .extract[T] that doesn't require parsing .class files

### ISSUE THREAD

**Issue by onelson** [json4s/json4s#247]
Not exactly sure what I'm looking for beyond a pointer in some direction.

I'm coming from https://groups.google.com/d/msg/robovm/WIw_Nj4NAqg/_LoozcgMj04J where I worked through a series of issues getting my app working under RoboVM, during which I saw that it looked like json4s was hoping to parse .class files when extracting json to case class.
(tl;dr on that google groups thread: once RoboVM converts the java code to native, there are no .class files left to parse)

I'm hoping there is something I can do, either through switching parsers, or explicitly defining formats, that will allow me to avoid the need for scalap at runtime.

I'm trying to use the jackson parser, mostly because it seemed to be well supported from `dispatch` but switching would not be a big deal, especially if it'll mean I don't have to explicitly write out serializers and deserializers for each of my case classes (of which there are many).

Anything you can share?

Cheers,
Owen

**Comment by onelson** [comment]
Went digging and stumbled across muster, which from the looks of the readme might not be maintained right now (not sure).

Seems to be working for my use case, however. Compile-time reflection is just what the doctor ordered when you are translating bytecode into native this or that.
Going to proceed down this track and see where it leads for now.

**Comment by casualjim** [comment]
There are some things that don't fully work in muster. Now I don't know how much of that just got fixed by scala versions.
As stated in the readme, personally I'm not doing Scala anymore, or much jvm work in the foreseeable future.
Now the reason json4s uses scalasig, is more historical and then lack of time to replace it. 

Prior to scala 2.10 there was no runtime reflection for scala. The scala primitives in generics would all have their types erased. This we could fix by writing a compiler plugin which seemed like a very complex thing to do, or by using scalasig to parse the class files and get the info from there. 
This allowed us to support things like List[Option[Int]].

**Comment by onelson** [comment]
Indeed. I don't suppose you can ballpark the non-fully working things for me? Most of my data structures are not elaborate, and not too much nesting.

Perhaps the reflection can be improved dramatically for 2.11+ since I'm under the impression there has been much work done there recently. Still for my use, class files are out (at runtime). They simply won't exist, so I need something that kicks in at compile-time.

I think for the time being, muster is my best shot (unless someone can pitch me another option). If it should get me to a place where I can ship some prototypes, I can loop back around and see about improving json4s!

**Comment by casualjim** [comment]
there is one that I know of :)

https://github.com/json4s/muster/issues/14

**Comment by onelson** [comment]
OK, I guess that's all anyone has to say! Thanks again for the insight, @casualjim !
