### ISSUE TITLE
JSON4s "2"

### ISSUE THREAD

**Issue by mdedetrich** [json4s/json4s#266]
So I have personally started a rewrite of JSON4s, I am going to quickly detail the rationale and reasoning behind why
1. Current Json4s heavily depends on reflection (thats how extraction works). This has both been historically problematic (scala's internal issues with reflection), has lower performance, and throws errors at runtime when they could be thrown at compile time. The reflection would be replaced with Macro's
2. API Design can use improvements. While the core JSON4s API is fantastic, stuff like `DefaultFormats` could be really designed better and simpler (no reason to have a `DefaultFormats` class which requires its own specific appender. I am thinking of something closer to `Slick`'s `MappedColumnType` for defining custom serialisation for formats)
3. Want to remove as many dependencies as possible. Completely ideal scenario is to have 0 dependencies (apart from `QuasiQuotes` which is just used for macros), however I can live with having to use something like `Jawn` strictly for parsing. There will strictly be no Java dependencies, which gets to the last point
4. Modular design. Anything that doesn't satisfy the above will be in separate modules. Stuff like `mongo`/`scalaz` etc etc support will as their own projects. Support for reflection can even be added in, but it would as a separate module

**Support for Scala.js**
One of the defining reasons why I wan't to support Json4s is that I wont it to work with `Scala.js`. All of the above needs to be done in order to do this (`Scala.js` doesn't really support reflection, and it doesn't support Java, either as source code or as dependencies)

The above points also can also help the possible scenario of having json4s added into Scala's `stdlib`. Although unlikely, the above points do greatly increase its chances of being included (particularly no/minimal dependencies)

Spoke with @seratch on github about this, and he is generally ok with it. The ticket is here if people want to add anything, currently its in really alpha stage (i.e. not compiling), but I will most likely upload as a separate project once enough of it has been done so its useful.

**Comment by seratch** [comment]
FYI:

>Spoke with @seratch on github about this, and he is generally ok with it.

I've replied as below on the gitter chat:

I'm basically working on json4s project to just keep maintenance mode. IMO, json4s 3.x should be source code compatible with older versions. Existing users including me would hope so.

I think we have three options on this topic.

A) Rewriting from scratch toward json4s 4.0
B) Creating new library under json4s org as same as casualjim's muster (no longer maintained)
C) Creating new library in other place (basically no relationship with json4s project)

Actually json4s project is inactive now. If you're very passionate about rebuilding json4s project toward the next major version (4.x), that's fine for me too.

**Comment by mdedetrich** [comment]
Yup, so I am basically going for option A, so it is going to be a total rewrite. Will keep this ticket updated as I progress on the core stuff, and will upload it to github once its usable

**Comment by rossabaker** [comment]
I agree, this effort would make the most sense as a 4.0.  I'm very grateful for @seratch's maintenance work, and also agree with the flaws detailed by @mdedetrich.

To give some history on the project, json4s was born a fork of lift-json (with the author's blessing) when there were no other major Scala libraries for JSON, and the community did not want to be tied to Lift's slow release cycle, especially when it came to new releases of Scala.  The project hoped to provide a de facto standard, as lift-json was at the time, but other people had other ideas for how a JSON library should look -- many of them very good!

With so many good Scala libraries in the community, it seems silly to create a new major version instead of letting one die.  But there are reasons I'm not prepared to fully embrace the others, well done as they are:

1) Argonaut's functional principles are wonderful, but the tight coupling to Scalaz is troublesome for those who hope to migrate to Cats someday.  A lean library with modules to provide the instances that make us FP folks happy would avoid that nasty civil war.

2) There is also much to admire in the design of play-json and spray-json, but there has been rumbling out of Typesafe for years about picking a favorite and/or merging, and still no progress or roadmap.  This leaves me nervous about the future stability of either.

I'm excited to see someone leading the charge.  I'd like to see it developed on a branch to get early feedback, as I'd hate @mdedetrich to go to all this work only to find strong disagreement from others.  Is there any reason we couldn't open up a 4.x branch and keep this effort in the open?

**Comment by mdedetrich** [comment]
@rossabaker The only reason why its a separate project is because it is a re-write from scratch. The only code that is common is the AST and the DSL, the rest I am writing from scratch. I have no issue regarding branching, but the branch would be really divergent. Also in the github world, it appears that complete rerwrites are often made as new projects (i.e. coffeescript redux). The other final reason is the project structure is very different to the current one (also as an aim to get it to work on `Scala.js`, plus the inclusion of macros)

I do however agree with trying to get the project up ASAP so other people can help and provide feedback. If you guys think its better served being in an alternate branch, I am all good with that as well.

Personally, the main reason I like `Json4s` is a pragmatic one, it has the most practical API that I have used (which also reflects that we are dealing with unstructured data). Plus it being separate from frameworks means it has been adopted in many places, i.e. as a recent example, `slick-pg` which is an extension of postgres for slick as a wrapper for `JSON4`s for postgres's data `JSON`/`JSONB` datatype

**Comment by rossabaker** [comment]
I've done rewrites before on a clean branch.  That shows life to the existing user base and provides a nice history for people browsing tags, but cross-contaminates the issue tracker.  Pros and cons, I guess.

**Comment by mdedetrich** [comment]
Ill go with whatever people are happy with, I don't have any issue in making a new branch and cleaning it

**Comment by rossabaker** [comment]
If your work is blocked on permissions, feel free to start a new repo.  We can always pull that repo into a blank branch once we get ownership issues straightened out.

**Comment by mdedetrich** [comment]
Ok cool, I will start from a fresh repo (for now), and I will place a link it on this issue. Hopefully will have something out in around a week

**Comment by seratch** [comment]
I just created 3.4 branch and made it the default. I'm not sure how we should work on 4.0 project yet. Are you going to work on the 4.0 project in another repository?

**Comment by mdedetrich** [comment]
@rossabaker Thoughts on this?

I like the different repo mainly from the POV is its going to be done from scratch, but I am open to making a new empty branch

**Comment by rossabaker** [comment]
From a source management perspective, a clean branch in the same repo is no big deal.  The bigger question is: do we want issues for json4s-4 to appear intermingled with json4s-3?  This would be nice, so lingering issues can be addressed and closed in the rewrite.  Although it will be confusing for a while, and probably requires some discipline in terms of tagging issues.

My advice: If same issues, same repo.  If clean start on issues, different repo.

**Comment by mdedetrich** [comment]
Well it is going to be a complete rewrite, so many of the issues may not apply (or might automatically be solved), so I am leaning more towards a new repo.

You can also refer to other issues, its just that they wont appear in some of the stats.

**Comment by magnolia-k** [comment]
Since the discussion of this issue has stopped, it will be closed once. Reopen if you have any issues to discuss.
