### ISSUE TITLE
Java interop: Package names should be rid of the word "native"

### ISSUE THREAD

**Issue by basdek** [json4s/json4s#357]
Since the word native is a [reserved keyword](https://docs.oracle.com/javase/tutorial/java/nutsandbolts/_keywords.html) entire parts of the library can not be imported from Java. 

This can of course partly be blamed on the not too smart lexical parser of Java that in principle should not expect the `native` keyword after an `import` statement. However, this is hugely impractical.

**Comment by magnolia-k** [comment]
As you point out, the native package name is not appropriate, but changing it from now will have too much impact
Also, since the native version of the parser does not correctly handle the latest JSON specifications, it is better to use the jackson package if possible.

This issue will be closed, but if further discussion is needed, reopen it.
