### ISSUE TITLE
java.util.List

### ISSUE THREAD

**Issue by trbngr** [json4s/json4s#366]
I have a java class generated from avro-tools that has a couple of List<E> fields. json4s will not deserialize them.

I dug into the code (and don't have time to write tests today) and it seems that it would be trivial to add support for this in the [CollectionBuilder](https://github.com/json4s/json4s/blob/3.4/core/src/main/scala/org/json4s/Extraction.scala#L423)

As a work-around, I created some intermediate case classes which I don't want to keep around.

**Comment by magnolia-k** [comment]
@trbngr 

Objects cannot be created for java.util.List in Json4s at present.

On the other hand, since the code for supporting ArrayList is included, it succeeds for ArrayList. However, it does not support LinkedList.

https://github.com/json4s/json4s/blob/a14670386d33831f1f18c7606e3f968457e3a465/core/src/main/scala/org/json4s/Extraction.scala#L466

It is necessary to add a function to automatically generate ArrayList for java.util.List.

Patches are welcome.
