### ISSUE TITLE
Json4s non-deterministic behaviour in picking constructor while extracting

### ISSUE THREAD

**Issue by yarulan** [json4s/json4s#371]
If we have overloaded constructors with the same parameter name

``` scala
case class Foo(x: Bar) {
  def this(x: Baz) = this(Bar(x.baz))
}

case class Bar(bar: Int)
case class Baz(baz: Int)
```

then which one is picked is based on the order constructors are returned from `java.lang.Class#getConstructors`. And that means everything works fine locally but doesn't work on staging. One of these fails, which one is environmentally dependent

``` scala
serialization.read[Foo](""" {"x": {"bar": 42}} """)
serialization.read[Foo](""" {"x": {"baz": 42}} """)
```

I would be happy if extraction worked for such cases, but I would also accept `AmbiguousConstructorsException` or at least make your constructor choosing algorithm deterministic.
[Test case](https://github.com/yarulan/misc/commit/41419add4a9246311f5916bd494896e2d4fe1b11).

**Comment by mccartney** [comment]
After spending several hours of debugging a flaky issue (with multiple constructors for the same case class) I found this issue. And I can state:
- the problem is still there in `3.6.8`
- and the non-determinism might be even more fragile that between environments.  https://github.com/mccartney/json4s-deser-examples is my simple code which shows the environment non-determinism, i.e.:
- **quite consistently** (majority of the time) the code there shows `2,4,4` on my OSX machine and `4,2,4` on my Linux machine (in AWS EC2)
- but I **also observe** some single-machine non-determinism, i.e. saw the other result in OSX too, although very rare. I am yet to pinpoint that. I suspect it depends on the other load on the machine.
