### ISSUE TITLE
JsonMethods.parse interface change

### ISSUE THREAD

**Issue by leonfl** [json4s/json4s#433]
### json4s version
3.4.1
### scala version
2.11.8
### jdk version
1.8

Our package using json4s 3.2.11, and another product will depends our package but they using json4s 3.4.1, then build crash with error:
Exception in thread "main" java.lang.NoSuchMethodError: org.json4s.jackson.JsonMethods$.parse(Lorg/json4s/JsonInput;Z)Lorg/json4s/JsonAST$JValue;

After check, I fount that in json4s 3.4.1, the interface `parse()` add a new parameter. I think this is not very good for interface change, the old interface should be reserved, right?

**Comment by seratch** [comment]
It's ok to fix the problem on the method by applying your fix so far. But, in general, it's dangerous to mix libraries that depend on multiple json4s version in 3.x. I highly recommend not to do that.

Since json4s 3.3, we guarantee binary compatibility between patch releases (patch version: y of 3.x.y) such as 3.4.0 & 3.4.1. But we don't (cannot) guarantee binary compatibility between 3.x releases.

**Comment by seratch** [comment]
>It's ok to fix the problem on the method by applying your fix so far.

Unfortunately, your fix cannot compile.

**Comment by xuwei-k** [comment]
closing because 
> we don't (cannot) guarantee binary compatibility between 3.x releases.

**Comment by minhlab** [comment]
This issue costed me a few days. I was using XGBoost on a Spark cluster when this error turned up. XGBoost apparently used an older version of json4s than what was available in my cluster but it wasn't easy at all to figure out.
