### ISSUE TITLE
Deserialized inner case classes cannot be compared with case classes initialized in code

### ISSUE THREAD

**Issue by svenallers** [json4s/json4s#564]
When deserializing case classes that are defined inside of a class then those cannot be compared with objects of the same class that were initialized in code.

Example:
```scala
import org.json4s.{DefaultFormats, Formats}
import org.json4s.native.JsonMethods
import org.scalatest.{Matchers, WordSpec}

class MySpec extends WordSpec with Matchers{
  implicit val formats: Formats = DefaultFormats

  "This test fails" in {
    val json = JsonMethods.parse("""{
      |  "id": "1234"
      |}
    """.stripMargin)
    
    val model = json.extract[MyModel]
    model.id shouldBe "1234" //This check still works
    model shouldBe MyModel("1234") //This check fails
  }

  case class MyModel(id: String)
}
```

I fixed it for me by defining the case classes outside of the class. But I still think that this is a bug and should be fixed.

### json4s version
3.6.2

### scala version
2.12.8

### jdk version
1.8.0_191

**Comment by mario-galic** [comment]
Replicated with `"org.json4s" %% "json4s-native" % "3.6.5"` and Scala 2.12.8: https://stackoverflow.com/questions/55890176/structural-equality-affected-by-location-of-case-class-definition-after-deserial

**Comment by magnolia-k** [comment]
I think this is not a bug.

For more details, please refer to the README "Serializing classes defined in traits or classes".

Scala requires an instance of the outer class in order to instantiate nested inner classes.

Json4s automatically creates an instance of the outer class (in above example, it creates an instance of MySpec). Since the equivalence check of the case class is checked together with the instances of the outer class, they are judged to be different value.

To get around this, give an instance of the outer class as described in the README "Serializing classes defined in traits or classes".

**Comment by magnolia-k** [comment]
@svenallers 
solved the problem? 
Can this issue be closed?

**Comment by svenallers** [comment]
I would leave it open to you. If this is expected behavior, then feel free to close it. I solved it for myself by not using inner classes for my use case. I just would like to spread awareness that it is pretty easy to step into this trap and I think it will look like a bug many people as it is not really obvious why it behaves like that to most people.
