### ISSUE TITLE
New release with jackson-databind: 2.9.8

### ISSUE THREAD

**Issue by sadu99** [json4s/json4s#586]
### jdk version 1.8

Hi, would it be possible to release a new json4s version with jackson-databind bumped to 2.9.8? I see this change already exists in master.

**Comment by seratch** [comment]
I can work on it but if you're really in a hurry, you should be able to use json4s 3.6.4 with jackson-databind 2.9.8 because jackson-databind 2.9.6 and 2.9.8 must be binary compatible.

>Patch releases need to fully replaceable and have no changes to source or binary compatibility
https://github.com/FasterXML/jackson/wiki/Jackson-Releases#general

You can explicitly add jackson 2.9.8 in your sbt build settings.

**Comment by sadu99** [comment]
Thanks for the reply - I'll try adding the updated dependency explicitly.

**Comment by seratch** [comment]
json4s 3.6.5 has been deployed. The jars will be available on the Maven Central repos very soon. https://github.com/json4s/json4s/compare/v3.6.4...v3.6.5

**Comment by sadu99** [comment]
Thanks @seratch 😄
