### ISSUE TITLE
json4s-jackson 4.0.0 not released for Scala 3

### ISSUE THREAD

**Issue by thesamet** [json4s/json4s#809]
### json4s version
4.0.0

### scala version
3.0.0

It seems that json4s-jackson is disabled in the current build.

**Comment by xuwei-k** [comment]
Short answer: please use `json4s-jackson-core` if possible.

`json4s-core` reflection based serialization/deserialization does not work with Scala 3 due to some reasons.

- Manifest https://github.com/lampepfl/dotty/issues/9482
- json4s use `scalap`. scalap read [`scala.reflect.ScalaSignature`](https://github.com/scala/scala/blob/8f903f78b86e168c197842e7f3d20d2d4018542c/src/library/scala/reflect/ScalaSignature.java) annotation. but Scala 3 use `TASTy` instead of `ScalaSignature`.

So, I have created new modules `json4s-jackson-core` and `json4s-native-core` which only simple parser/printer features. no runtime reflection 😃 .

### json4s 3.6

![old](https://user-images.githubusercontent.com/389787/121797066-bf15d700-cc58-11eb-93a3-139210b96d3a.png)

## json4s 4.0

`core`, `json4s-jackson`, `json4s-native`  and `ext` is dead since Scala 3. 😢 
 
![new](https://user-images.githubusercontent.com/389787/121797064-bd4c1380-cc58-11eb-803b-9d499f8d6942.png)

**Comment by xuwei-k** [comment]
https://github.com/lampepfl/dotty/pull/13142

**Comment by xuwei-k** [comment]
- https://repo1.maven.org/maven2/org/json4s/json4s-native_3/
- https://repo1.maven.org/maven2/org/json4s/json4s-jackson_3/

4.0.2 released

**Comment by xuwei-k** [comment]
https://github.com/json4s/json4s/issues/827 😢 😇
